[project]
name = "data-sources"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "duckdb>=1.4.0",
    "feedparser>=6.0.12",
    "google-genai>=1.43.0",
    "lxml>=6.0.2",
    "polars>=1.34.0",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_sources"]


