[project]
name = "data-access"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.4.1",
    "polars>=1.34.0",

]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/data_access"]


